[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18" # Match your Node.js version

# Required for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"