[build]
  command = "npm run build"
  publish = ".next"  # Changed from "out" to ".next"
  functions = "functions"  # Add this if using API routes

[build.environment]
  NODE_VERSION = "18"  # Must match your .nvmrc or local version

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enableNextJs = true
    enableImageOptimization = false  # Disable if causing issues